# scripts/audit/75-hero.sh
# the README hero: the tape matches its template, the gif is under the byte ceiling, the render is newer than the tape
#
# A SOURCED FRAGMENT of scripts/audit-core.sh — not a standalone script. It runs in the
# dispatcher's shell and uses its state: the PASS/SKIP/FAIL counters, $HERE (already cd'd
# to), the SCOPE_* flags, META_ALLOWLIST/META_PREFIXES, MANIFEST_PATHS/VENDOR_PATHS (parsed
# by 10-manifest.sh, §1), and the pass/skip/skip_env/fail/fail_detail/hdr/have helpers from
# scripts/lib/common.sh. NO EXIT TRAP HERE: the dispatcher installs the one that reaps the
# backgrounded behavioral suite, and `trap … EXIT` REPLACES rather than appends. The §-ids
# below are the STABLE gate ids — CLAUDE.md, CONTRIBUTING.md, VENDORING.md, PORTABILITY.md
# and the CHANGELOG all cite them — and the split did not renumber one; the NN- in this
# file's name carries run order only. See the header of scripts/audit-core.sh for the
# contract.

# ── 9j. README hero tape drift (hero.tape.in ↔ this repo's assets/demo.tape) ──
# assets/demo.tape is GENERATED by scripts/gen-hero-tape.sh from assets/hero.tape.in,
# assets/hero-repos.txt and theme/palette.toml (#698) — the same generated-source answer
# §9d gives colour, §9g the alias tables, §9h the porting matrix and §9i the desktop pair.
#
# IT REPLACES A CLAIM. assets/README.md already asserted the hero was reproducible — "re-run
# the command after any prompt or tooling change and the hero updates, no manual
# re-recording" — while the tape itself filmed the WRONG REPO: `cd ~/…/dotfiles-MacBook`,
# inside dotfiles-core. Nothing could catch that, because nothing derived the tape from
# anything. It also carried `Set Theme "TokyoNight"` — a fourth place the theme was named by
# hand, and the only one naming an upstream preset instead of theme/palette.toml's resolved
# table, so the hero could stay "Tokyo Night" while Core's chrome moved. Both are now
# rendered, so both are now gated.
#
# THE GATE IS TWO FACTS, §9g's shape. --check exits 1 when the rendered tape differs from
# what is on disk (the template or the registry edited without regenerating, or the tape
# edited by hand). Anything else is "cannot run" — a missing template, a malformed registry
# row, a palette key that is not a hex — and is rendered as a different failure, so a broken
# gate is never read as a stale tape.
#
# NO ENVIRONMENT SKIP, unlike §9h and §9i, and that is the point of the default scope: the
# ten SIBLING tapes are #698's follow-up (sequenced after #667) and are reached only under
# --fleet, so this run's inputs are all this repo's own files. It can always answer.
#
# ALWAYS ON and NOT SCOPE-GUARDED, for §9d's reasons: pure bash + awk, so it can never SKIP;
# and a `.tape` is INERT to ci-classify.sh, so the very push that hand-edits the tape arrives
# here as --scope none and must still be gated.
hdr "README hero tape drift (gen-hero-tape.sh --check)"
_gh_out="$("$HERE/scripts/gen-hero-tape.sh" --check 2>&1)" && _gh_rc=0 || _gh_rc=$?
if ((_gh_rc == 0)); then
  pass "gen-hero-tape (assets/demo.tape matches assets/hero.tape.in + the palette)"
elif ((_gh_rc == 1)); then
  fail "README hero tape drift — assets/demo.tape no longer matches its template; run: make gen-hero-tape"
  fail_detail "$_gh_out"
else
  fail "gen-hero-tape.sh --check could not run (exit $_gh_rc) — the template or registry is missing, a row is malformed, or the palette is unreadable; the drift gate checked NOTHING this run"
  fail_detail "$_gh_out"
fi
unset _gh_out _gh_rc

# ── 9k. README hero byte ceiling (the rendered gif) ──────────────────────────
# assets/demo.gif was 1.8 MB for a ~25-second clip, and assets/README.md documented the
# remedy — `gifsicle -O3 --lossy=80` — that nothing applied (#698). ONE heavy gif is a
# preference; eleven, once every public repo has a hero, is a policy, so the number is asserted
# rather than described in prose no gate reads.
#
# THE CEILING FOLLOWS THE TAPE. gen-hero-tape.sh --check-size reads `Output <path>` out of
# each in-scope tape and weighs THAT file, so a tape that renames its output cannot slip a
# heavy gif past a hardcoded assets/demo.gif. A tape naming no output is exit 2, not a pass.
#
# A GIF THAT IS NOT RENDERED YET IS A NOTE SKIP, NOT A PASS. #698 sequences the ten sibling
# heroes after #667; under the default scope only this repo is weighed, and this repo's tape
# and gif are both mandatory — README.md's [product-screenshot] points at the latter, so an
# absent file is a broken front page. Separate from §9j because the two fail for unrelated
# reasons and the fix lines differ — regenerate the tape, versus render or shrink the gif.
#
# THE HEADLINE STAYS GENERIC. Exit 1 covers THREE causes here — over the ceiling, a missing
# gif, a missing local tape — so naming one of them in the ✗ line misreports the other two
# (#862 review). The script already prints the specific remedy per row; fail_detail carries
# it through verbatim, which is exactly the division of labour fail_detail exists for.
hdr "README hero byte ceiling (gen-hero-tape.sh --check-size)"
_ghs_out="$("$HERE/scripts/gen-hero-tape.sh" --check-size 2>&1)" && _ghs_rc=0 || _ghs_rc=$?
if ((_ghs_rc == 0)); then
  pass "gen-hero-tape --check-size (every rendered hero is under the ceiling)"
elif ((_ghs_rc == 1)); then
  fail "README hero size check failed — see below; the remedy differs by cause (an oversized gif is shortened and re-optimized, a missing one is rendered)"
  fail_detail "$_ghs_out"
else
  fail "gen-hero-tape.sh --check-size could not run (exit $_ghs_rc) — a tape names no Output, or the registry/template is unreadable; the size gate weighed NOTHING this run"
  fail_detail "$_ghs_out"
fi
unset _ghs_out _ghs_rc

# ── 9l. README hero render date (the gif is newer than the tape that made it) ─
# §9j proves the tape tracks its template; §9k weighs the gif and checks it exists. Both
# were GREEN across #862 while this repo's front page showed a hero of the WRONG REPO: the
# tape had been rewritten to film a dotfiles-core checkout, the gif was left as the
# 2026-07-06 render of `~/code/dotfiles/dotfiles-MacBook`, and nothing compared the two
# (#877). A generated script whose OUTPUT nobody dates is generated in name only — the
# property assets/README.md advertises ("re-run the command and the hero updates") was the
# one thing neither gate checked.
#
# GIT HISTORY IS THE CLOCK, not mtime — mtime does not survive a clone, so on a fresh CI
# checkout every hero would date to the second it was written. The script's own header
# carries the full argument; what matters here is the exit contract: 1 is a gif older than
# its tape (or a missing one — README.md's [product-screenshot] points at it), and 3 is a
# tree that CANNOT date anything (shallow, not a checkout, unrelated histories). Three is an
# ENVIRONMENT skip, §9h's posture, and it is a skip and not a pass because #821 is the
# standing lesson: a history-dependent check on a tree without history must say so, never
# go green because the evidence was absent. CI's audit job takes fetch-depth: 0, so it is
# never that tree.
#
# WIRED ONLY ONCE IT COULD BE GREEN. #870 landed --check-render and deliberately left it out
# of this file: the check was correct and RED, and greening it needs vhs on a host matching
# the row, so wiring it then would have blocked every unrelated `make sync` behind a render
# nobody could do from CI. #877 re-rendered the gif; this is the one block that entry promised.
#
# ALWAYS ON and NOT SCOPE-GUARDED, for §9j's reason: a `.tape` and a `.gif` are both INERT
# to ci-classify.sh, so the push that rewrites the tape and forgets the render arrives here
# as --scope none and must still be gated.
hdr "README hero render date (gen-hero-tape.sh --check-render)"
_ghr_out="$("$HERE/scripts/gen-hero-tape.sh" --check-render 2>&1)" && _ghr_rc=0 || _ghr_rc=$?
if ((_ghr_rc == 0)); then
  pass "gen-hero-tape --check-render (every rendered hero is newer than the tape that made it)"
elif ((_ghr_rc == 1)); then
  fail "README hero render is stale — see below; the tape changed after the gif was last rendered (or the gif is missing). Re-render on a host matching the row (vhs assets/demo.tape, then the gifsicle pass assets/README.md documents) and commit the gif"
  fail_detail "$_ghr_out"
elif ((_ghr_rc == 3)); then
  skip_env "README hero render date (no usable git history to date the gif against — shallow clone or not a checkout; not covered by this run)"
else
  fail "gen-hero-tape.sh --check-render could not run (exit $_ghr_rc) — a tape names no Output, or the registry/template is unreadable; the render-date gate dated NOTHING this run"
  fail_detail "$_ghr_out"
fi
unset _ghr_out _ghr_rc
